spring.config.import=optional:file:.env.properties
spring.application.name=gyan
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gyan}
# spring.datasource.url=jdbc:postgresql://postgres:5432/gyan
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# spring.elasticsearch.uris=http://elasticsearch:9200
spring.elasticsearch.uris=${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}

# document upload config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads
file.max-size=10485760
file.allowed-types=application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/plain


# kafka config
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
# spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=document-service
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# groq AI config
groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions

# embedding service
embedding.service.url=${EMBEDDING_SERVICE_URL:http://localhost:8000}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173}

# logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n
